# Generated by Django 4.1.5 on 2023-01-30 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='coins',
            new_name='eth',
        ),
    ]
