# Generated by Django 4.1.5 on 2023-01-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='players_username',
            field=models.JSONField(default={}),
        ),
    ]
